### PR TITLE
improve config.sh, fix ncurses detection

### PR DESCRIPTION
**Pull request by rofl0r**

### CODE REVIEW

**Comment by rofl0r** [comment]
(tested with dash, the most restrictive/posixly_correct shell)

**Comment by rofl0r** [comment]
just ftr, the ncurses detection before this commit was broken when using netbsd-curses, also the transparency and wget_wch checks could never complete successfully because the required C/LDFLAGS for ncurses were not used for those checks.

**Comment by rofl0r** [comment]
@X-Ryl669 : would you mind testing this and provide your feedback? thanks!

**Comment by ttcdt** [comment]
This patch breaks everything and generates a non-working mp:

tiny@hell:~/src/mp-5.x$ ./mp-5
mp_core.mpsl: file not found

Didn't investigate further but from the make output I see it's
generating mp.tar but expecting mp.zip.

11/11/20 14:40, rofl0r:

**Pull request merged**
